### ISSUE TITLE
Defines are not transitively collected from implementation_deps dependencies.

### ISSUE THREAD

**Issue by furtib** [Ericsson/rules_codechecker#305]
**Describe the bug**
C/C++ compile flags named `defines` are not collected from implementation_deps dependencies.
This can cause a compilation error during analysis.

**Versions**
* `CodeChecker 6.28.2`
* `bazel 8.5.1`
* ba752b067ea7beaab40916be00f7e1837ad7436e

**To Reproduce**
Run the skylib tests introduced in #284.

**Expected behaviour**
The mock attribute, to be in the compilation database.
